### ISSUE TITLE
not an issue, but i can provide computation to scale up for 1B

### ISSUE THREAD

**Issue by huseinzol05** [MahmoudAshraf97/ctc-forced-aligner#46]
As the title, not an issue but I think I can help to provide computation to replicate this great work for MMS 1B also, or you think 300M already decent and not required for 1B?

**Comment by MahmoudAshraf97** [comment]
Table 4 in https://arxiv.org/abs/2303.00747 suggests that larger models do not necessarily perform better, it depends on the training data more than model size.
Perhaps you should benchmark it yourself, I think if the 1B model was trained on more multilingual data then it might perform better, otherwise I'd expect similar performance, you can also try scaling down to wav2vec2base and see how it does

**Comment by MahmoudAshraf97** [comment]
I meant speech in different languages, not necessarily multilingual in the same speech, as you know wav2vec2 is a phoneme model, so training on different languages might make it more robust in aligning
